services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: lucasnigro/iam-ai-bot-api:1.0.5   # 👈 nombre fijo de la imagen
    container_name: iam-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      HF_HOME: /app/.cache/huggingface
    volumes:
      # Montá sólo si querés editar documentos/índice en caliente;
      # si ya los copiaste a la imagen, podés quitar estas líneas.
      - ./data/documentos:/app/data/documentos:ro
      - ./faiss_index:/app/faiss_index
      - ./hf_cache:/app/.cache/huggingface
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-http://localhost:8000}
    image: lucasnigro/iam-ai-bot-web:1.0.5   # 👈 nombre fijo de la imagen
    container_name: iam-web
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
